name: Build Jekyll Site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name  "github-actions[bot]"
        git checkout --orphan gh-pages
        git rm -rf .
        git commit --allow-empty -m "initial commit"
        git push origin gh-pages
